name: Deploy on LocalStack

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Start LocalStack
        run: |
          pip install localstack
          docker pull localstack/localstack
          localstack start -d
          echo "Waiting for LocalStack startup..."
          localstack wait -t 30

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Show LocalStack Logs
        run: docker logs $(docker ps --filter ancestor=localstack/localstack --format "{{.ID}}")
