name: Terraform Security Scan

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  security_check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.0

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@master
